#!/bin/sh
# proj-klient
#

PORT=8080
SERVER="http://s0:$PORT"

# START

ROOMS_URL="$SERVER/room/get"

room=$(curl -sfL $ROOMS_URL)

url="$SERVER/?id=$room"

echo "$url" >&2

firefox -new-tab $link >/dev/null 2>&1 &

exit
