#!/bin/sh
# proj-start
# Uruchamia serwer laplace i otwiera w przeglądarce stronę do udostępniania,
# parviaij 2023

#BIN=/usr/local/sbin		# Docelowa instalacja

PORT=8080			
URL="http://localhost:$PORT/?stream=1"

BROWSER="/usr/bin/firefox -new-tab "

proj=laplace
# START

[ "$USER" = "root" ] && fatal "Należy uruchamiać bez sudo"

sudo pkill -f $proj

sudo $proj --tls=false >/dev/null & #2>&1 &

pid=$! ; echo "PID=$pid" ; ps -p $pid

warn -M 'Proszę kliknąć guzik "Start stream" i wybrać udostępniane okno'

$BROWSER "$URL" >/dev/null 2>&1 &

exit
