#!/bin/sh
# proj-start
# Uruchamia serwer laplace i otwiera w przeglądarce stronę do udostępniania,
# parviaij 2023

#BIN=/usr/local/sbin		# Docelowa instalacja

PORT=8080			
URL="http://localhost:$PORT/?stream=1"

BROWSER="/usr/bin/firefox -new-tab "

# START

# [ "$USER" = "root" ] && fatal "Należy uruchamiać bez sudo"

sudo systemctl start projector

warn -M 'Proszę kliknąć guzik "Start stream" i wybrać udostępniane okno'

$BROWSER "$URL" >/dev/null 2>&1 &

exit
