#!/bin/sh
# proj-start
# Uruchamia serwer laplace i otwiera w przeglądarce stronę do udostępniania,
# parviaj 2023

#BIN=/usr/local/sbin		# Docelowa instalacja

PORT=443			# 55443 i bez root
URL="http://localhost:$PORT/?stream=1"

BROWSER="/usr/bin/firefox -new-tab"

# START

bin=${0%/*}			# /pub/Linux/Arch/zetis/bin /proj-start
bin=/pub/Linux/Arch/zetis/bin

[ "$USER" = "root" ] && fatal "Należy uruchamiać bez sudo"

sudo pkill -f laplace

laplace="$bin/proj/bin/laplace"

#ls -l $laplace ; exit

sudo $laplace --tls=false >/dev/null & #2>&1 &

pid=$! ; echo "PID=$pid" ; ps -p $pid

warn -M 'Proszę kliknąć guzik "Start stream" i wybrać udostępniane okno'

$BROWSER "$URL" >/dev/null 2>&1 &

exit
