#!/bin/sh
# proj-klient
# Skrypt ułatwiający oglądanie ekranu udostępnionego w aplikacji projector

PORT=8080
SERVER="https://s2:$PORT"

# START

ROOMS_URL="$SERVER/room/get"

room=$(curl -sf $ROOMS_URL)

url="$SERVER/?id=$room"

echo "$url" >&2

google-chrome --ignore-certificate-errors -new-tab $url >/dev/null 2>&1 &

exit
